'use client'

import Link from 'next/link'
import Layout from '@/components/layout/Layout'
import { useCart } from '@/lib/cart'
import { formatCurrency } from '@/lib/currency'

export default function CartPage() {
  const { items, isReady, subtotal, currency, updateQuantity, removeItem, clearCart } = useCart()
  if (!isReady) return <Layout><div className="mx-auto max-w-4xl px-4 py-16 text-center text-gray-600">Loading cart…</div></Layout>
  if (items.length === 0) return <Layout><div className="mx-auto max-w-4xl px-4 py-16 text-center"><h1 className="text-3xl font-bold text-gray-900">Your cart is empty</h1><p className="mt-3 text-gray-600">Add a product to get started.</p><Link href="/shop" className="mt-6 inline-block rounded-md bg-blue-600 px-5 py-3 font-medium text-white hover:bg-blue-700">Browse products</Link></div></Layout>

  return <Layout><div className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><div className="mb-8 flex items-center justify-between"><div><h1 className="text-3xl font-bold text-gray-900">Your cart</h1><p className="mt-2 text-gray-600">Review your items before checkout.</p></div><button type="button" onClick={clearCart} className="text-sm font-medium text-red-600 hover:text-red-700">Clear cart</button></div><div className="space-y-4">{items.map((item) => <div key={item.productId} className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-semibold text-gray-900">{item.name}</h2><p className="mt-1 text-sm text-gray-600">{formatCurrency(item.price, item.currency)} each</p></div><div className="flex items-center gap-4"><div className="flex items-center rounded-md border border-gray-300"><button type="button" onClick={() => updateQuantity(item.productId, item.quantity - 1)} className="px-3 py-2 text-gray-700 hover:bg-gray-50" aria-label={`Decrease ${item.name}`}>−</button><span className="min-w-10 text-center text-sm font-medium">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.productId, item.quantity + 1)} disabled={item.quantity >= item.inventory} className="px-3 py-2 text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:text-gray-300" aria-label={`Increase ${item.name}`}>+</button></div><p className="min-w-24 text-right font-semibold text-gray-900">{formatCurrency(item.price * item.quantity, item.currency)}</p><button type="button" onClick={() => removeItem(item.productId)} className="text-sm font-medium text-red-600 hover:text-red-700">Remove</button></div></div></div>)}</div><div className="mt-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between text-lg font-semibold text-gray-900"><span>Subtotal</span><span>{formatCurrency(subtotal, currency)}</span></div><p className="mt-2 text-sm text-gray-500">Final prices and stock are confirmed securely at checkout.</p><div className="mt-6 flex justify-end gap-3"><Link href="/shop" className="rounded-md border border-gray-300 px-5 py-3 text-sm font-medium text-gray-700 hover:bg-gray-50">Continue shopping</Link><Link href="/checkout" className="rounded-md bg-blue-600 px-5 py-3 text-sm font-medium text-white hover:bg-blue-700">Proceed to checkout</Link></div></div></div></Layout>
}
