'use client'

import Link from 'next/link'
import Layout from '@/components/layout/Layout'
import { useCart } from '@/lib/cart'
import { formatCurrency } from '@/lib/currency'

export default function CartPage() {
  const { items, isReady, subtotal, currency, updateQuantity, removeItem, clearCart } = useCart()
  if (!isReady) return <Layout><div className="mx-auto max-w-4xl px-4 py-20 text-center text-slate-400">Loading cart…</div></Layout>
  if (items.length === 0) return <Layout><div className="mx-auto max-w-4xl px-4 py-24 text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Your cart</p><h1 className="mt-4 text-4xl font-semibold text-white">Nothing here yet.</h1><p className="mt-3 text-slate-400">Add something considered to get started.</p><Link href="/shop" className="mt-8 inline-block rounded-full bg-white px-5 py-3 font-semibold text-slate-950 hover:bg-cyan-100">Browse products</Link></div></Layout>
  return <Layout><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Your cart</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-white">Ready when you are.</h1><p className="mt-2 text-slate-400">Review your selections before checkout.</p></div><button type="button" onClick={clearCart} className="text-sm font-medium text-slate-400 hover:text-rose-300">Clear cart</button></div><div className="mt-10 space-y-3">{items.map((item) => <div key={item.productId} className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-white/[0.05] p-4 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-4">{item.imageUrl ? <img src={item.imageUrl} alt="" className="h-20 w-20 shrink-0 rounded-xl object-cover" /> : <div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-blue-100 to-cyan-100 text-xl font-bold text-blue-700">{item.name.slice(0, 1)}</div>}<div className="min-w-0"><h2 className="truncate font-semibold text-white">{item.name}</h2><p className="mt-1 text-sm text-slate-400">{formatCurrency(item.price, item.currency)} each</p></div></div><div className="flex items-center justify-between gap-4 sm:justify-end"><div className="flex items-center rounded-full border border-white/15 bg-slate-950"><button type="button" onClick={() => updateQuantity(item.productId, item.quantity - 1)} className="px-3 py-2 text-slate-300 hover:text-white" aria-label={`Decrease ${item.name}`}>−</button><span className="min-w-8 text-center text-sm font-semibold text-white">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.productId, item.quantity + 1)} disabled={item.quantity >= item.inventory} className="px-3 py-2 text-slate-300 hover:text-white" aria-label={`Increase ${item.name}`}>+</button></div><p className="min-w-24 text-right font-semibold text-white">{formatCurrency(item.price * item.quantity, item.currency)}</p><button type="button" onClick={() => removeItem(item.productId)} className="text-sm text-slate-400 hover:text-rose-300">Remove</button></div></div>)}</div><div className="mt-6 rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.08] p-6"><div className="flex items-center justify-between text-lg font-semibold text-white"><span>Subtotal</span><span>{formatCurrency(subtotal, currency)}</span></div><p className="mt-2 text-sm text-slate-400">Final prices and stock are confirmed securely at checkout.</p><div className="mt-6 flex flex-wrap justify-end gap-3"><Link href="/shop" className="rounded-full border border-white/15 px-5 py-3 text-sm font-semibold text-white hover:bg-white/10">Continue shopping</Link><Link href="/checkout" className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-100">Checkout</Link></div></div></div></Layout>
}
